### ISSUE TITLE
您好师兄，有些疑问想请教一下。

### ISSUE THREAD

**Issue by Th1sbb** [qyp2000/XPSR#6]
您好师兄，我在提取低级语义信息时遇到如下报错：AttributeError: 'InternLMXComposerTokenizer' object has no attribute 'sp_model'。请问师兄方便跟我说一下如何解决吗？祝师兄身体健康，科研顺利！

**Comment by hzhXue** [comment]
您好，我想问一下您是怎么解决的，如果解决了的话能否让我看一下你的环境是什么样的

**Comment by Th1sbb** [comment]
> 您好，我想问一下您是怎么解决的，如果解决了的话能否让我看一下你的环境是什么样的
您好，由于重装了系统，我环境忘记掉了，但是我可以将当时的全部文件发给你，不知道会不会对你有所帮助。

**Comment by hzhXue** [comment]
可以可以，谢谢，你当时跑通了这个吗

**Comment by hzhXue** [comment]
可以加个wx私聊一下吗

**Comment by Th1sbb** [comment]
> 可以加个wx私聊一下吗

可以，我加你吧，到时候你把wx号删一下

**Comment by hzhXue** [comment]
好，我的wx是15720971902

**Comment by Th1sbb** [comment]
> 好，我的wx是15720971902

ok了
